services:
  - type: web
    name: videoweb-backend
    env: docker
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    disk:
      type: persistent
      name: runtime-data
      mountPath: /app/runtime
      sizeGB: 1
    healthCheckPath: /
    numInstances: 1
